### ISSUE TITLE
exception when second user is changed on 3.0.1

### ISSUE THREAD

**Issue by c3ph3us** [temasek/Changelogs#6]
01-20 05:26:53.620 6907-6907/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.cyanogenmod.trebuchet, PID: 6907
                                                 java.lang.RuntimeException: Unable to start receiver com.android.launcher3.ThemeChangedReceiver: java.lang.IllegalStateException: LauncherAppState inited before app context set
                                                     at android.app.ActivityThread.handleReceiver(ActivityThread.java:2776)
                                                     at android.app.ActivityThread.-wrap14(ActivityThread.java)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1440)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:148)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5470)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                  Caused by: java.lang.IllegalStateException: LauncherAppState inited before app context set
                                                     at com.android.launcher3.LauncherAppState.<init>(LauncherAppState.java:77)
                                                     at com.android.launcher3.LauncherAppState.getInstance(LauncherAppState.java:55)
                                                     at com.android.launcher3.ThemeChangedReceiver.onReceive(ThemeChangedReceiver.java:36)
                                                     at android.app.ActivityThread.handleReceiver(ActivityThread.java:2769)
                                                     at android.app.ActivityThread.-wrap14(ActivityThread.java) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1440) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:148) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5470) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by c3ph3us** [comment]
also when create user and multi user support in supersu is enabled 

01-20 05:26:54.516 7225-7225/? E/dex2oat: Failed to create oat file: /data/dalvik-cache/arm/system@app@SuperSU@SuperSU.apk@classes.dex: Permission denied
