### ISSUE TITLE
multi user gallery exception  on 3.0.1

### ISSUE THREAD

**Issue by c3ph3us** [temasek/Changelogs#7]
01-20 06:06:32.208 812-1414/? E/DatabaseUtils: Writing exception to parcel
                                               java.lang.SecurityException: get package info: Neither user 1110039 nor current process has android.permission.INTERACT_ACROSS_USERS.
                                                   at android.app.ContextImpl.enforce(ContextImpl.java:1450)
                                                   at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:1482)
                                                   at com.android.server.pm.PackageManagerService.enforceCrossUserPermission(PackageManagerService.java:3437)
                                                   at com.android.server.pm.PackageManagerService.getPackageInfo(PackageManagerService.java:2851)
                                                   at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:130)
                                                   at com.android.providers.settings.SettingsProvider.getCallingPackageInfoOrThrow(SettingsProvider.java:1161)
                                                   at com.android.providers.settings.SettingsProvider.enforceRestrictedSystemSettingsMutationForCallingPackage(SettingsProvider.java:1125)
                                                   at com.android.providers.settings.SettingsProvider.mutateSystemSetting(SettingsProvider.java:991)
                                                   at com.android.providers.settings.SettingsProvider.insertSystemSetting(SettingsProvider.java:959)
                                                   at com.android.providers.settings.SettingsProvider.call(SettingsProvider.java:260)
                                                   at android.content.ContentProvider$Transport.call(ContentProvider.java:398)
                                                   at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:283)
                                                   at android.os.Binder.execTransact(Binder.java:453)
01-20 06:06:32.212 5242-5242/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.android.gallery3d, PID: 5242
                                                 java.lang.RuntimeException: Unable to start receiver org.codeaurora.gallery3d.video.DmReceiver: java.lang.SecurityException: get package info: Neither user 1110039 nor current process has android.permission.INTERACT_ACROSS_USERS.
                                                     at android.app.ActivityThread.handleReceiver(ActivityThread.java:2776)
                                                     at android.app.ActivityThread.-wrap14(ActivityThread.java)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1440)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:148)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5470)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                  Caused by: java.lang.SecurityException: get package info: Neither user 1110039 nor current process has android.permission.INTERACT_ACROSS_USERS.
                                                     at android.os.Parcel.readException(Parcel.java:1637)
                                                     at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
                                                     at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
                                                     at android.content.ContentProviderProxy.call(ContentProviderNative.java:646)
                                                     at android.provider.Settings$NameValueCache.putStringForUser(Settings.java:1340)
                                                     at android.provider.Settings$System.putStringForUser(Settings.java:1715)
                                                     at android.provider.Settings$System.putString(Settings.java:1698)
                                                     at org.codeaurora.gallery3d.video.DmReceiver.onReceive(DmReceiver.java:39)
                                                     at android.app.ActivityThread.handleReceiver(ActivityThread.java:2769)
                                                     at android.app.ActivityThread.-wrap14(ActivityThread.java) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1440) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:148) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5470) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by c3ph3us** [comment]
and related 

01-20 06:06:16.920 812-1414/? E/DatabaseUtils: Writing exception to parcel
                                               java.lang.SecurityException: Permission Denial: get/set setting for user asks to run as user 0 but is calling from user 11; this requires android.permission.INTERACT_ACROSS_USERS_FULL
                                                   at com.android.server.am.ActivityManagerService.handleIncomingUser(ActivityManagerService.java:16158)
                                                   at com.android.server.am.ActivityManagerService.handleIncomingUser(ActivityManagerService.java:16079)
                                                   at android.app.ActivityManager.handleIncomingUser(ActivityManager.java:2748)
                                                   at com.android.providers.settings.SettingsProvider.resolveCallingUserIdEnforcingPermissionsLocked(SettingsProvider.java:1288)
                                                   at com.android.providers.settings.SettingsProvider.getSecureSetting(SettingsProvider.java:764)
                                                   at com.android.providers.settings.SettingsProvider.call(SettingsProvider.java:237)
                                                   at android.content.ContentProvider$Transport.call(ContentProvider.java:398)
                                                   at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:283)
                                                   at android.os.Binder.execTransact(Binder.java:453)

**Comment by Ravinnpawar** [comment]
any one solved this issue?>
